- hosts: all
  become: yes
  vars:
    packages:
      - vim
      - wget
      - curl
      - htop
  tasks:
    - name: Ensure a list of packages installed
      apt:
        name: "{{packages}}"
        state: present
